dependencies {
  implementation connie()
  api pamela()
  
  implementation group: 'org.apache.xmlgraphics', name: 'batik-svggen', version: '1.13',  {
       exclude group: "xml-apis", module: "xml-apis"
  }
  implementation group: 'org.apache.xmlgraphics', name: 'batik-dom', version: '1.13',  {
       exclude group: "xml-apis", module: "xml-apis"
  }
  
  implementation project(':diana-geom')
  implementation project(':diana-api')
  implementation project(':diana-core')
  testImplementation project(':diana-core-test')

  api ginaSwing()
  testImplementation ginaTest()
  testImplementation ginaReplayTest()
}
