/**
 *
 * Copyright (c) 2026, Openflexo
 *
 * This file is part of Diana-palettes, a component of the software infrastructure
 * developed at Openflexo.
 *
 *
 * Openflexo is dual-licensed under the European Union Public License (EUPL, either
 * version 1.1 of the License, or any later version ), which is available at
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * and the GNU General Public License (GPL, either version 3 of the License, or any
 * later version), which is available at http://www.gnu.org/licenses/gpl.html .
 *
 * You can redistribute it and/or modify under the terms of either of these licenses
 *
 * If you choose to redistribute it and/or modify under the terms of the GNU GPL, you
 * must include the following additional permission.
 *
 *          Additional permission under GNU GPL version 3 section 7
 *
 *          If you modify this Program, or any covered work, by linking or
 *          combining it with software containing parts covered by the terms
 *          of EPL 1.0, the licensors of this Program grant you additional permission
 *          to convey the resulting work. *
 *
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * See http://www.openflexo.org/license.html for details.
 *
 *
 * Please contact Openflexo (openflexo-contacts@openflexo.org)
 * or visit www.openflexo.org if you need additional information.
 *
 */

package org.openflexo.diana.palettes;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.awt.image.BufferedImage;

import javax.imageio.ImageIO;

import org.junit.BeforeClass;
import org.junit.Test;
import org.openflexo.diana.BackgroundImageBackgroundStyle;
import org.openflexo.diana.DianaModelFactory;
import org.openflexo.diana.DianaModelFactoryImpl;
import org.openflexo.diana.PaletteElementSpecification;
import org.openflexo.pamela.converter.RelativePathResourceConverter;
import org.openflexo.rm.Resource;
import org.openflexo.rm.ResourceLocator;

/**
 * Checks the Emoji palette generated by {@link FluentEmojiPaletteGenerator}: each element reads, and its image resolves and loads
 * 
 * @author sylvain
 */
public class TestEmojiPalette {

	private static DianaModelFactory factory;

	@BeforeClass
	public static void setUp() throws Exception {
		factory = new DianaModelFactoryImpl();
		factory.addConverter(new RelativePathResourceConverter(
				ResourceLocator.locateResource(FluentEmojiPaletteGenerator.PALETTE_DIRECTORY).getContainer().getContainer()));
	}

	@Test
	public void testPaletteContents() {
		Resource directory = ResourceLocator.locateResource(FluentEmojiPaletteGenerator.PALETTE_DIRECTORY);
		assertNotNull(directory);
		assertEquals(FluentEmojiPaletteGenerator.EMOJIS.size(), directory.getContents().size());
		// The MIT license of Fluent Emoji requires its notice to be kept with the images
		assertNotNull(ResourceLocator.locateResource(FluentEmojiPaletteGenerator.IMAGES_DIRECTORY + "/LICENSE"));
	}

	@Test
	public void testElementImagesLoad() throws Exception {
		int index = 0;
		for (String emoji : FluentEmojiPaletteGenerator.EMOJIS) {
			String fileName = FluentEmojiPaletteGenerator.fileName(emoji);
			Resource resource = ResourceLocator.locateResource(FluentEmojiPaletteGenerator.PALETTE_DIRECTORY + "/" + fileName + ".pel");
			assertNotNull(fileName, resource);
			PaletteElementSpecification spec = (PaletteElementSpecification) factory.deserialize(resource.openInputStream());
			assertEquals(fileName, index++, spec.getIndex().intValue());
			assertTrue(fileName, spec.getGraphicalRepresentation().getBackground() instanceof BackgroundImageBackgroundStyle);
			// The label would hide the image
			TestDianaPalettes.assertFloatingLabel(fileName, spec.getGraphicalRepresentation(), true);
			Resource imageResource = ((BackgroundImageBackgroundStyle) spec.getGraphicalRepresentation().getBackground())
					.getImageResource();
			assertNotNull(fileName + ": image not resolved", imageResource);
			BufferedImage image = ImageIO.read(imageResource.openInputStream());
			assertNotNull(fileName + ": image not read", image);
			assertEquals(FluentEmojiPaletteGenerator.IMAGE_SIZE, image.getWidth());
			assertEquals(FluentEmojiPaletteGenerator.IMAGE_SIZE, image.getHeight());
		}
	}
}
